# Generated by Django 5.0.6 on 2024-07-02 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinValueValidator(6000000000), django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
    ]
