# Generated by Django 5.0.6 on 2024-07-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('jobid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20)),
                ('companyname', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
