# Generated by Django 5.0.6 on 2024-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_options_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='prerequisites',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
