# Generated by Django 5.0.6 on 2024-07-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jobdetails_details_jobdetails_prerequisites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdetails',
            options={'verbose_name_plural': 'Job Details'},
        ),
    ]
