# Generated by Django 5.0.6 on 2024-07-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_jobdetails_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='user',
            new_name='userid',
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
            options={
                'verbose_name_plural': 'Session',
            },
        ),
    ]
