# Generated by Django 5.0.6 on 2024-07-03 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_user_jobdetails_userid_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinValueValidator(6000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('current_company', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('resume', models.FileField(blank=True, null=True, upload_to='job_pdfs/')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobdetails')),
            ],
            options={
                'verbose_name_plural': 'Candidate',
            },
        ),
    ]
