# Generated by Django 5.0.6 on 2024-07-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobdetails'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
