# Generated by Django 5.0.6 on 2024-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_candidate_id_candidate_jobid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobid',
            field=models.PositiveIntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
