# Generated by Django 5.0.6 on 2024-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_jobdetails_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
